#!/bin/sh
if [ -z "$2" ];
then
    LD_PRELOAD="$PWD/build/libcustomnew.so" $1
else
    if [ $2 = "-d" ]; then
        LD_PRELOAD="$PWD/build/libcustomnewdebug.so" $1
    else
        if [ $2 = "-gdbn" ]; then
            LD_PRELOAD="$PWD/build/libcustomnew.so" gdb --args $1
        else
            if [ $2 = "-gdb" ]; then
                LD_PRELOAD="$PWD/build/libcustomnewdebug.so" gdb --args $1
            else
                echo "Wrong 2nd argument"
            fi
        fi
    fi
fi
