#!/bin/sh
if [ -z "$2" ];
then
    LD_PRELOAD="/usr/local/lib/libcustomnew.so" $1
else
    if [ $2 = "-gdbn" ]; then
        LD_PRELOAD="/usr/local/lib/libcustomnew.so" gdb --args $1
    else
        echo "Wrong 2nd argument"
    fi
fi
